server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: core-api

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:core_api}
    username: ${DB_USER:core_api}
    password: ${DB_PASSWORD:core_api}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    com.twitchspamdetector.coreapi: DEBUG
